# Generated by Django 4.2.17 on 2024-12-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad',
            field=models.CharField(default='ejemplo: gramos', max_length=100),
        ),
    ]
