# Generated by Django 4.2.17 on 2025-01-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0003_unidad_alter_ingrediente_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad',
            field=models.CharField(default='ejemplo: gramos', max_length=100),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='unidad',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
