# Generated by Django 4.2.17 on 2025-01-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0004_alter_ingrediente_unidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetaingrediente',
            name='unidad',
        ),
    ]
