# Generated by Django 4.2.17 on 2025-01-02 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0005_remove_recetaingrediente_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetaingrediente',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='calculos.ingrediente'),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='calculos.receta'),
        ),
    ]
